In [11]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
import os
import pandas as pd

In [13]:
#from ordinaloss.utils.datasets import ImageFolder, create_transform_pipeline
from ordinaloss.utils.pretrained_models import classification_model_densenet, classification_model_resnet, classification_model_vgg
from ordinaloss.utils.utils import create_ordinal_cost_matrix


from ordinaloss.engine.model_engine import OrdinalEngine, OrdinalEngineNew
from ordinaloss.utils.datasets import data_load

from ordinaloss.utils.loss_utils import SinimLoss, GirlsLoss, CSCELoss


import matplotlib.pyplot as plt

from torch.utils.data import DataLoader
from torch.optim import Adam, SGD
import torch
import numpy as np

device = "cuda:1" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [45]:
model = classification_model_vgg("vgg19", num_classes = 5)
cost_matrix = create_ordinal_cost_matrix(5, cost_distance=3, diagonal_value=20)
loaders, _, _ = data_load("../datasets/kneeKL224/", 16)

from ordinaloss.nextgen_engine import model_engine

engine = model_engine.OrdinalEngine(
    model=model, loss_fn=CSCELoss(cost_matrix), 
    device=device, loaders=loaders, n_classes=5,
    use_lr_scheduler=True,# scheduler_lambda_fn = my_lambda_scheduler,
    optimizer_fn=SGD, lr=1.0e-3, weight_decay=5.0e-2)

loaded ordinaloss.nextgen_engine.metrics
loaded ordinaloss.nextgen_engine.model_engine


In [46]:
engine._train_epoch()

Training, epoch 0:   0%|          | 1/362 [00:15<1:30:18, 15.01s/it, accuracy=0.188, loss=39.8]

tensor([2., 0., 7., 5., 2.])


Training, epoch 0:   1%|          | 2/362 [00:23<1:08:47, 11.47s/it, accuracy=0.25, loss=37.4] 

tensor([ 9.,  1., 15.,  5.,  2.])


Training, epoch 0:   1%|          | 3/362 [00:32<1:01:00, 10.20s/it, accuracy=0.354, loss=45.9]

tensor([25.,  1., 15.,  5.,  2.])


Training, epoch 0:   1%|          | 4/362 [00:41<57:18,  9.60s/it, accuracy=0.328, loss=45.3]  

tensor([25.,  7., 15., 15.,  2.])


Training, epoch 0:   1%|          | 4/362 [00:51<1:17:06, 12.92s/it, accuracy=0.328, loss=45.3]


KeyboardInterrupt: 

In [25]:
torch.tensor([0, 1,2,3,1,0]).bincount(minlength=5)

tensor([2, 2, 1, 1, 0])

In [27]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [32]:
engine._train_epoch()

loaded ordinaloss.nextgen_engine.metrics


[autoreload of ordinaloss.nextgen_engine.metrics failed: Traceback (most recent call last):
  File "c:\Users\imargolin\Anaconda3\envs\pytorch\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "c:\Users\imargolin\Anaconda3\envs\pytorch\lib\site-packages\IPython\extensions\autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "c:\Users\imargolin\Anaconda3\envs\pytorch\lib\site-packages\IPython\extensions\autoreload.py", line 347, in update_generic
    update(a, b)
  File "c:\Users\imargolin\Anaconda3\envs\pytorch\lib\site-packages\IPython\extensions\autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "c:\Users\imargolin\Anaconda3\envs\pytorch\lib\site-packages\IPython\extensions\autoreload.py", line 347, in update_generic
    update(a, b)
  File "c:\Users\imargolin\Anaconda3\envs\pytorch\lib\site-packages\IPython\extensions\autoreload.py"

AttributeError: 'OrdinalEngine' object has no attribute 'n_classes'

In [ ]:
from ordinaloss.utils.loss_utils import GirlsLoss, SinimLoss


def my_lambda_scheduler(epoch):
    return (0.9 ** (epoch // 5))

num_classes = 5
loaders, _, _ = data_load("../datasets/kneeKL224/", 16)


for diagonal_value in [7,9,13,20]:
    for cost_distance in [1,2,3,4]:

        model = classification_model_vgg("vgg19", num_classes=num_classes)
        cost_matrix = create_ordinal_cost_matrix(num_classes=num_classes, cost_distance=3, diagonal_value=diagonal_value)

        engine = OrdinalEngineNew(
            model=model, loss_fn=CSCELoss(cost_matrix), 
            device=device, loaders=loaders,
            use_lr_scheduler=True, scheduler_lambda_fn = my_lambda_scheduler,
            optimizer_fn=SGD, lr=1.0e-3, weight_decay=5.0e-2)

        engine.train(n_epochs=15)

loaded ordinaloss.utils.datasets
loaded ordinaloss.nextgen_engine.model_engine


loaded ordinaloss.nextgen_engine.model_engine


Training, epoch 0:   0%|          | 0/362 [00:01<?, ?it/s]


PicklingError: Can't pickle <function default_loader at 0x000002E0287EA700>: it's not the same object as ordinaloss.utils.datasets.default_loader